export const LOAD_PLANET_DATA_PENDING = 'softserve/LOAD_PLANET_DATA_PENDING';
export const LOAD_PLANET_DATA_SUCCESS = 'softserve/LOAD_PLANET_DATA_SUCCESS';
export const LOAD_PLANET_DATA_FAILURE = 'softserve/LOAD_PLANET_DATA_FAILURE';
export const LOAD_RESIDENT_PENDING = 'softserve/LOAD_RESIDENT_PENDING';
export const LOAD_RESIDENT_SUCCESS = 'softserve/LOAD_RESIDENT_SUCCESS';
export const LOAD_RESIDENT_FAILURE = 'softserve/LOAD_RESIDENT_FAILURE';
